/* iCSU Smart CI - Technical Account Strategist (TAS) persona examples.
   Reframes each module from the point of view of a Technical Account Strategist:
   the trusted technical advisor who owns the customer's technical health and
   roadmap, runs proactive risk management, drives architecture and reliability
   improvement, and connects delivery work to the customer's technical strategy.
   Keyed by module id, per language, with English as the fallback. app.js merges
   these into the module's role-based examples at render time, so a module's own
   `tasExample` field (if ever added to a data file) still takes precedence.
   Keep each entry a single <p> paragraph, consistent in length and tone with
   the other persona fields. */
window.TAS_EXAMPLES = {
  "en": {
    "intro": "<p>A Technical Account Strategist replaces reactive escalation management with a proactive Continuous Improvement cadence for the account. Rather than wait for the next Sev B, they baseline the customer's incident volume, run a Pareto on the telemetry, and drive one hypothesis per cycle into the technical roadmap. Three cycles later incidents are measurably down and the loop lives in the customer's own backlog. Owning a repeatable improvement rhythm — not a stream of tickets — is how the TAS shifts the relationship from firefighting to strategic technical health.</p>",
    "belts": "<p>A Technical Account Strategist uses the belt ladder to build durable capability inside the customer's engineering org so they depend less on outside help over time. Guiding two of the customer's SREs through Green Belt skilling on a real production problem yields both a measured improvement and in-house practitioners who can run the next cycle. The TAS treats belts as the formalization of capability the team is already demonstrating in the roadmap work. It's how a technical advisor makes their own influence compound rather than creating dependency.</p>",
    "ms-ci-cop": "<p>A Technical Account Strategist taps Continuous Improvement @ Microsoft to bring the customer battle-tested WAF playbooks instead of hand-crafted analysis. Reliability assessments, scoring, and remediation backlogs arrive peer-reviewed, so the TAS delivers a standard, defensible technical readout in hours rather than days. Patterns proven on this customer's estate — a Cosmos indexing fix, an ACR private-endpoint change — get contributed back and later surface as product improvements. The TAS's day-to-day work quietly makes the platform better for the account and everyone after it.</p>",
    "data-types": "<p>A Technical Account Strategist keeps the customer from green-lighting a big change on weak evidence. They separate a renewal forecast (theoretical) and a sign-in dip (circumstantial) from actual consumption and incident history (empirical and direct), and steer the technical decision toward the direct data. Coding qualitative signals like 'deployments feel risky' into counted themes turns anecdote into a measurable concern. Anchoring roadmap decisions on measured reality — and treating models as things to pressure-test — is how the TAS prevents confident moves in the wrong direction.</p>",
    "convergent-divergent": "<p>A Technical Account Strategist stops the customer's war room from converging instantly on 'it's the database — re-index it.' They hold the team in divergent mode first, building an Ishikawa across the 6 Ms — scale-in cold starts, RU throttling, DNS, retry storms, GC pauses — before judging any of them, then converge only on the direct data. That data often clears the database entirely. Separating generate-from-evaluate keeps the account from burning a cycle on the wrong fix and protects the customer's trust in the improvement process.</p>",
    "house-of-lean": "<p>A Technical Account Strategist uses the House of Lean to sequence the customer's technical roadmap correctly. When the customer has adopted tools piecemeal and gains never hold, the TAS diagnoses the missing foundation — no standardized work, so every squad diverges and improvements have no stable baseline. They plan the roadmap the right way: stabilize and standardize first, then strengthen flow and built-in quality toward the customer's goal of shorter lead time. The house keeps the TAS from strengthening pillars built on sand.</p>",
    "dmaic": "<p>A Technical Account Strategist runs DMAIC with the customer's reliability team to cut incidents from 8 a month to 2. Define aligns leadership on the charter; Measure baselines incident rate and MTTR from real data; Analyze uses a Pareto to trace 60% of incidents to one microservice timeout; Improve pilots a circuit-breaker; Control codifies the pattern in the customer's policy and runbooks. The tollgates keep the account from shipping a confident fix to the wrong problem, and the payoff is engineers spending time on features instead of firefighting.</p>",
    "pdca": "<p>A Technical Account Strategist installs PDCA as the customer's default for technical change. Every change becomes a falsifiable hypothesis — 'a warm pool drops P95 from 900ms to 500ms within a week because cold starts dominate the tail' — run small on a canary and checked against the prediction before it's standardized. Negative results become data, not embarrassment. Chaining these cycles, the TAS helps the customer compound small, trustworthy technical gains they can defend to their own leadership, replacing change-by-opinion with change-by-evidence.</p>",
    "a3": "<p>A Technical Account Strategist uses an A3 to break a stalled technical initiative where five stakeholders hold five versions of the problem. Building it together — background, current condition, goal, root-cause analysis, countermeasures, follow-up on one page — often reveals the 'performance problem' is really a capacity problem with a clear owner. The A3 becomes the account's living technical document: it drives the standup, records what was tried, and gives leadership a one-glance view of progress. One page keeps everyone honest about what the data supports.</p>",
    "failed-hypothesis": "<p>A Technical Account Strategist protects the customer's improvement culture when a carefully planned experiment doesn't move the metric. They run validity checks first — measurement trust, process stability, sample size, implementation fidelity — then treat a sound null result as a finding that eliminated a candidate cause. They ensure the customer reverts cleanly, documents the learning, and reports it transparently in a blameless culture, never torturing the data into a false win. A disciplined failed cycle still advances the account's technical investigation.</p>",
    "control-charts": "<p>A Technical Account Strategist stands up control charts (SPC) on the customer's own P95 latency in Azure Workbooks, with limits computed from their real data, so on-call stops chasing every blip. Now the team distinguishes a genuine signal — a point outside the limits, a sustained shift — from ordinary noise, and reacts only to the former. Over-reaction and alert fatigue drop, and real shifts become obvious. The TAS moves the account from tampering with a stable process to trusting a data-defined baseline.</p>",
    "process-capability": "<p>A Technical Account Strategist keeps the customer from committing to an SLO their system can't hold. Computing Cp and Cpk against the spec limits reveals a process centered fine but too variable to be consistent, which reframes the plan toward reducing variation before publishing the target. The TAS gives the customer's leadership a defensible capability figure, not a hopeful one, so the SLO they eventually commit to is one their process can genuinely sustain — protecting both reliability and credibility.</p>",
    "p-value": "<p>A Technical Account Strategist stops the customer from declaring victory on a lucky week. When an incident count drops after a change, they ask the p-value question: real signal, or the noise a fluctuating process produces anyway? Testing often shows the 'improvement' is within normal variation. Teaching the customer to ask 'signal or noise?' before standardizing keeps the account's technical decisions grounded in evidence and prevents the surprise when a prematurely celebrated metric drifts back.</p>",
    "value": "<p>A Technical Account Strategist steers the customer's engineering effort toward Value — what their end users would actually pay for — and away from internally important busywork. Examining the delivery pipeline through that lens surfaces whole activities that add cost without value, like gold-plating a report nobody reads. Redirecting that effort to the latency users actually feel sharpens where the customer spends its scarcest resource, engineering time. Value framing is how the TAS keeps the technical roadmap pointed at outcomes that matter.</p>",
    "voc": "<p>A Technical Account Strategist runs Voice of the Customer so the roadmap rests on what the customer's users actually need, not assumptions. Structured interviews and coded feedback often reveal the top pain isn't the debated feature backlog but an unpredictable deployment window blocking release plans. Turning verbatims into counted, ranked themes lets the TAS prioritize the roadmap by real frequency-weighted need. VOC replaces guessing at requirements with measuring them, keeping the account's technical investment aimed where it counts.</p>",
    "ctq": "<p>A Technical Account Strategist translates the customer's vague 'better performance' into a Critical-to-Quality characteristic: P95 checkout latency at or below 500ms, measured at the API gateway. A testable target makes every proposed architecture change judgeable and gives the customer's engineers a clear finish line and leadership a number to track. Turning fuzzy expectations into CTQs is what lets the TAS help the customer prove — not just claim — that a technical improvement actually landed.</p>",
    "copq": "<p>A Technical Account Strategist quantifies the customer's Cost of Poor Quality to unlock funding for reliability work leadership sees as a nuisance. Putting the rework, emergency escalations, churned trials, and lost engineer-hours in dollars usually shows the recurring incident class costs far more per quarter than the fix. That number reframes the customer's own finance conversation: the improvement becomes an obvious return, not a cost center. Making poor quality visible in money is how the TAS earns the mandate to harden the estate.</p>",
    "waste": "<p>A Technical Account Strategist walks the customer's value stream with the 8 wastes as a checklist, turning a vague 'we're slow' into named, prioritized targets: waiting on manual approvals, overproduced unused reports, defect rework, engineers hunting for access. Categorizing waste gives the customer a concrete backlog to work, and the TAS sequences the biggest one first so lead time drops immediately. The framework converts general technical frustration into an ownable, prioritized improvement plan the account can execute.</p>",
    "sipoc": "<p>A Technical Account Strategist ends a circular argument about a broken process by facilitating a SIPOC — Suppliers, Inputs, Process, Outputs, Customers — on one page in fifteen minutes. It exposes that two teams thought they owned the same handoff and that a key input arrives late from an unmapped upstream supplier. With boundaries agreed, the TAS can scope the technical improvement without relitigating what the process even is. SIPOC gives the account a shared picture before diving into architecture detail.</p>",
    "value-stream": "<p>A Technical Account Strategist maps the customer's full value stream and reveals why features take six weeks despite fast individual steps: the request sits idle in queues and handoffs. Making the customer's wait time impossible to ignore redirects effort from pushing engineers to code faster toward attacking the queues — batching approvals, removing a redundant sign-off — and halving lead time. Seeing the whole stream, not just the busy steps, is how the TAS points the roadmap at where delay actually lives.</p>",
    "pareto-chart": "<p>A Technical Account Strategist uses a Pareto chart of the customer's incident data to settle where to start: three signatures account for 70% of incidents. Rather than spreading thin across twenty issues, the TAS focuses the next cycle on the vital few, and fixing the top signature alone removes nearly half the pain. It gives the customer's leadership a defensible sequence — working the 20% of causes driving 80% of impact — and replaces 'everything is urgent' with data-backed focus.</p>",
    "ishikawa": "<p>A Technical Account Strategist runs an Ishikawa (fishbone) with the customer so they stop re-fixing the same defect. Forcing a divergent pass across the 6 Ms surfaces candidate causes the team never discussed — config drift, a runbook method gap, a measurement blind spot. Laying out all the branches before judging any prevents anchoring on the first guess, and converging with data often points to a branch that would have been skipped. The TAS gives the account a fuller map of why the problem happens.</p>",
    "5-whys": "<p>A Technical Account Strategist coaches the customer past incident reviews that stop at the first plausible cause — 'the pod ran out of memory, so we raised the limit' — only for the incident to return. Running 5 Whys on a real outage, each answer exposes the next layer until they reach a systemic root cause they can actually remove. The TAS moves the account from treating symptoms to fixing the condition that produced them, so the same incident does not come back.</p>",
    "6-ms": "<p>A Technical Account Strategist uses the 6 Ms — Machine, Method, Material, Measurement, People, Environment — as prompts when the customer's failure analysis keeps circling the same two ideas. Systematically walking ignored categories reveals the failure is a Measurement problem: the alert threshold was miscalibrated, not the service. The framework gives the customer's team a structured way to generate causes so blind spots surface before a fix ships. The TAS turns an unstructured argument into a complete, categorized search for the real driver.</p>",
    "fmea": "<p>A Technical Account Strategist runs an FMEA with the customer ahead of a critical launch to get in front of failures. Listing failure modes and scoring each by severity, occurrence, and detection into a risk priority number surfaces a high-RPN gap — a silent backup failure no one would notice until a restore was needed — and the TAS adds detection before go-live. The account's launch risk drops measurably, and leadership gets a prioritized, evidence-based list of what to harden first instead of a gut-feel gamble.</p>",
    "5s": "<p>A Technical Account Strategist applies 5S — Sort, Set in order, Shine, Standardize, Sustain — to the customer's cluttered repos, stale environments, and ambiguous configs. Removing dead branches and unused resources, giving everything a known place, and standardizing the layout drops onboarding from days to hours and makes anomalies stand out immediately. The Sustain step keeps it from sliding back. The TAS gives the account a visual, self-explanatory technical workplace that makes every later improvement easier to run.</p>",
    "standard-work": "<p>A Technical Account Strategist establishes standard work when the customer's teams each deploy slightly differently and every improvement evaporates as people move on. Capturing the current best-known method in versioned IaC and runbooks gives the account a stable baseline at last, so improvements stick by changing the standard rather than a person's habit, and new engineers onboard against documentation instead of tribal knowledge. The TAS treats standard work as the precondition for continuous improvement: without a baseline, nothing can be reliably improved.</p>",
    "gemba": "<p>A Technical Account Strategist gets the customer's leadership out of the dashboard and to the Gemba — sitting with on-call engineers during a real incident, watching a deployment unfold. There they discover friction no report captured: a manual step everyone quietly works around. Decisions grounded in what they see, not what they assume, land far better with the engineers doing the work and surface improvements that never appear in a summary. The TAS anchors the account's technical decisions in observed reality.</p>",
    "poka-yoke": "<p>A Technical Account Strategist ends the customer's recurring human-error outages — wrong environment variable, misconfigured tag, deploy to the wrong ring — not with another reminder but with poka-yoke. Policy denies the invalid configuration, a required field can't be left wrong, and the pipeline refuses a deploy that skips a gate, so the error rate for that class drops to zero. The TAS turns the account's reliability from a matter of individual vigilance into a property engineered into the platform itself.</p>",
    "andon-cord": "<p>A Technical Account Strategist introduces an Andon-cord model when the customer's engineers push through bad rollouts because halting feels like a personal failure. Automated canary analysis auto-pauses a progressive rollout on threshold breaches, and any engineer is authorized to stop a release without sign-off. Working with leadership to make pulls blameless — a stopped line celebrated as a defect contained — the TAS gets problems to surface during rollout instead of in production, making quality everyone's responsibility across the account.</p>",
    "takt-time": "<p>A Technical Account Strategist introduces takt time when the customer's team either overbuilds ahead of demand or scrambles to catch up. Sizing the cadence to the rate work genuinely arrives — not to how fast the team can push — makes capacity planning calmer and more predictable, ending both overproduction of unused features and starvation of needed ones. The TAS positions demand-paced work as the route to commitments leadership can actually trust, smoothing the account's delivery flow.</p>",
    "heijunka": "<p>A Technical Account Strategist applies heijunka when the customer's releases arrive in lumpy waves — quiet weeks then a crushing end-of-quarter surge that causes most incidents. Smoothing releases into a steady cadence exposes and removes the artificial deadlines behind the surge, and incident volume tied to big-bang releases falls sharply. Engineers stop swinging between idle and overloaded, and capacity is used evenly. Leveling the peaks and troughs makes every downstream step the TAS cares about — testing, deploying, on-call — more stable.</p>",
    "one-piece-flow": "<p>A Technical Account Strategist moves the customer from big-batch monthly releases toward one-piece flow: small changes shipped continuously through trunk-based delivery. Each change is easy to test, trace, and roll back, so mean time to detect and recover drops dramatically and a failed deploy affects one small change, not a month of bundled work. The TAS uses small batches to turn the account's releases from a high-stakes event into a routine, low-risk habit that keeps the system flowing.</p>",
    "supermarket": "<p>A Technical Account Strategist introduces a supermarket — a controlled, replenished buffer of ready work — when the customer's downstream teams keep getting starved or flooded. Work is pulled only as capacity opens and the buffer is replenished to a set level, decoupling upstream and downstream pace without overproducing. The account's flow steadies and feast-or-famine handoffs disappear. The TAS gives the customer's teams a simple, visible signal for when to build and when to hold, replacing guesswork with a controlled pull.</p>",
    "pull-vs-push": "<p>A Technical Account Strategist shifts the customer from a schedule-driven push system — where queues pile up and priorities blur — to a pull system driven by real demand and capacity. Engineers pull the next most important item when ready instead of drowning under everything assigned at once, so work-in-progress falls and throughput rises. The TAS uses the pull model to stop the account's system from overloading its own people, aligning technical effort with reality and making delivery predictable.</p>",
    "limit-wip": "<p>A Technical Account Strategist counters the customer's belief that starting more finishes more — where everything is perpetually 90% done — with explicit WIP limits. Capping items in progress forces the team to finish before it starts, and counterintuitively throughput rises and lead time falls as context-switching and half-done work stop clogging the flow. The TAS uses WIP limits to expose the account's real bottleneck instead of hiding it under a mountain of started-but-unfinished work.</p>",
    "kaizen": "<p>A Technical Account Strategist runs a focused Kaizen event on a nagging, well-understood problem that never rises to the customer's roadmap. A few days, a small cross-functional group, one clear target, and a real improvement ships by week's end because the scope is tight and the team owns it end-to-end. The TAS uses the quick win to prove continuous improvement produces tangible results fast, building the account's appetite and momentum for a larger, sustained program.</p>",
    "kanban": "<p>A Technical Account Strategist stands up a Kanban board when the customer's work is invisible and bottlenecks are only obvious in hindsight. Making every item, its stage, and where it's stuck visible surfaces blockers early, makes WIP controllable, and runs the standup off the board instead of memory. The TAS gives the account a shared, real-time picture of flow that makes overload and delay impossible to ignore — a lightweight mechanism to manage continuous technical work without a heavyweight process.</p>",
    "hoshin-kanri": "<p>A Technical Account Strategist uses Hoshin Kanri and its X-matrix to reconnect the customer's technical strategy with daily work when leadership's annual goals never reach the sprint. Linking top objectives to the specific initiatives, metrics, and owners that deliver them lets every team see how its work ladders up and leadership see which initiatives actually move the goals. The TAS uses it to stop technical effort from scattering across pet projects and concentrate it on the few things that matter most.</p>",
    "project-charter": "<p>A Technical Account Strategist starts every improvement with a project charter — problem statement, scope, measurable goal, and stakeholders on one page — before work begins. The charter stops scope creep, gives the customer's team a shared definition of success, and settles 'is this in or out?' debates. A few minutes of charter discipline up front saves the account weeks of drift and gives leadership a clear, agreed basis to sponsor the work and judge its result. It's how the TAS keeps technical initiatives focused.</p>"
  }
};
