/* iCSU Smart CI - Services Solutions Seller (SSS) persona examples.
   Reframes each module from the point of view of a Services Solutions Seller:
   how continuous-improvement thinking helps qualify, shape, position and close
   Microsoft services engagements, tie work to measurable business value, and
   grow durable consumption. Keyed by module id, per language, with English as
   the fallback. app.js merges these into the module's role-based examples at
   render time, so a module's own `sssExample` field (if ever added to a data
   file) still takes precedence. Keep each entry a single <p> paragraph,
   consistent in length and tone with the other persona fields. */
window.SSS_EXAMPLES = {
  "en": {
    "intro": "<p>A Services Solutions Seller stops pitching one-off projects and starts selling an outcome: a repeatable Continuous Improvement cadence the customer can measure. Instead of a fixed-scope statement of work that ends when the deliverable ships, they frame a 6-week loop that baselines a real pain, tests one hypothesis per cycle, and reports movement in the customer's own metrics. The deal becomes easy to justify because value is proven every cycle, not promised at the end. Selling the loop rather than the artifact turns a single transaction into a durable, renewable engagement.</p>",
    "belts": "<p>A Services Solutions Seller uses the Lean Six Sigma belt ladder as a credible skilling offer customers recognize — especially in regulated industries. Rather than selling seats in a course, they position belt progression as capability the customer's team builds on a real problem, with a measured result as the certification project. The belt gives the seller a tangible, outcome-anchored talking point and a natural expansion path: White and Yellow awareness today, Green and Black capability engagements tomorrow. Credentials that trail real results are far easier to sell than training for its own sake.</p>",
    "ms-ci-cop": "<p>A Services Solutions Seller leans on Continuous Improvement @ Microsoft to shorten the sales cycle: assessments, scoring, and remediation backlogs come from battle-tested WAF playbooks, so the customer gets a standard, peer-reviewed engagement in hours instead of a bespoke one in days. That speed-to-value is a differentiator the seller can put in the proposal. Better still, patterns proven on one account feed back into the community and reappear as reusable offers, so the seller is always positioning field-validated work rather than reinventing a pitch each time.</p>",
    "data-types": "<p>A Services Solutions Seller qualifies a deal by sorting the customer's evidence by type. A renewal forecast is <strong>theoretical</strong>, a dip in a proxy metric is <strong>circumstantial</strong>, and only measured consumption and incident history is <strong>empirical and direct</strong>. Anchoring the business case on direct data — not a hopeful model — makes the proposal defensible in front of a skeptical procurement or finance stakeholder. Knowing which kind of data backs the opportunity keeps the seller from committing to a value story the customer's own numbers won't support.</p>",
    "convergent-divergent": "<p>A Services Solutions Seller resists the room's rush to converge on 'you just need product X.' They stay divergent in discovery first — mapping the customer's real problems across categories before scoping any solution — then converge only on the engagement the evidence actually justifies. Separating discovery from prescription keeps the seller from over-scoping a deal the customer will later resent, or under-scoping one that won't deliver. The discipline builds trust: the customer sees a solution shaped by their situation, not a pre-packaged pitch.</p>",
    "house-of-lean": "<p>A Services Solutions Seller uses the House of Lean to sequence a multi-phase services roadmap the customer can buy in stages. When a prospect has adopted tools piecemeal with no lasting gain, the seller diagnoses the missing foundation — stability and standardized work — and positions a stabilize-first engagement before selling flow and quality work on top. The house gives the seller a credible architecture for a land-and-expand motion: each phase strengthens a part of the structure and creates the natural need for the next.</p>",
    "dmaic": "<p>A Services Solutions Seller shapes an engagement around DMAIC so the customer can see exactly what they're buying at each tollgate. Define scopes the charter and the measurable goal; Measure establishes the baseline; Analyze finds the driver; Improve pilots the fix; Control locks in the gain. Structuring the statement of work by phase makes the value legible and de-risks the purchase — the customer funds the next phase only after the tollgate proves the last one worked. DMAIC turns a vague 'improve reliability' ask into a fundable, staged plan.</p>",
    "pdca": "<p>A Services Solutions Seller frames delivery as chained PDCA cycles so the customer buys proven progress, not promises. Each change is a falsifiable hypothesis, run small and checked against a prediction before it scales — which means the seller can show measured movement at every review. Negative results become data that sharpens the next cycle rather than sunk cost. Positioning the engagement as a learning loop makes renewal an easy conversation: the customer has watched value accrue cycle by cycle in their own metrics.</p>",
    "a3": "<p>A Services Solutions Seller uses an A3 as a one-page qualification and alignment tool. Building it with the customer — background, current condition, goal, root cause, countermeasures, follow-up — forces five scattered stakeholders onto a single shared story and often reveals the real problem is not the one the RFP described. That clarity lets the seller scope the right engagement instead of the assumed one. The A3 doubles as an executive-ready artifact that makes the value case obvious at a glance and speeds the approval.</p>",
    "failed-hypothesis": "<p>A Services Solutions Seller protects the relationship when a piloted change doesn't move the metric. Rather than spin a null result, they position it honestly as a finding that eliminated a candidate and sharpened the next cycle — which is exactly what the customer paid a disciplined partner for. Framing disconfirming evidence as progress, not failure, builds the trust that renews contracts. A seller who can sell the value of a well-run failed experiment is selling capability, not luck.</p>",
    "control-charts": "<p>A Services Solutions Seller uses control charts to reframe a customer's over-reaction problem into a sellable improvement. When on-call teams chase every blip, the seller proposes an SPC-based engagement that separates real signal from ordinary noise and cuts alert fatigue. The chart gives the seller a crisp before-and-after story — fewer false reactions, faster response to genuine shifts — that quantifies the value of the work. It turns a fuzzy 'reduce noise' desire into a measurable outcome the proposal can promise and prove.</p>",
    "process-capability": "<p>A Services Solutions Seller uses Cp and Cpk to size an opportunity honestly. If a customer wants to commit to an SLO their process can't hold, the capability numbers reveal the gap — and become the business case for a variation-reduction engagement first. Selling against a real capability figure, not a hopeful target, keeps the seller from promising an outcome delivery can't meet. The number both scopes the deal correctly and gives the customer a defensible reason to fund it.</p>",
    "p-value": "<p>A Services Solutions Seller uses the signal-versus-noise question to keep a value story credible. Before claiming an engagement 'cut incidents,' they check whether the drop is a real signal or normal variation the process would produce anyway. Overclaiming a lucky week erodes trust when the metric drifts back; a defensible, evidence-tested result earns the renewal. Grounding the value narrative in significance, not coincidence, is what separates a durable services relationship from a one-time win the customer later doubts.</p>",
    "value": "<p>A Services Solutions Seller defines the offer through the customer's Value — what they would genuinely pay for — and prices the engagement to the outcome, not the activity. Examining the customer's pipeline through that lens surfaces high-value problems worth solving and low-value busywork to leave alone. Anchoring the proposal on end-user value the customer actually feels makes the price easy to justify and the deal easy to defend internally. Value framing is how the seller connects services spend to business results.</p>",
    "voc": "<p>A Services Solutions Seller runs Voice of the Customer discovery instead of assuming the RFP captured the real need. Structured interviews and coded feedback often reveal the top pain is not the feature everyone debated but something unglamorous and expensive — an unpredictable release window, say. Turning verbatims into counted, ranked themes gives the seller an evidence-based value case and the right engagement to propose. VOC replaces guessing at the customer's priorities with measuring them, so the deal targets what actually matters.</p>",
    "ctq": "<p>A Services Solutions Seller turns a customer's vague 'we need better performance' into a Critical-to-Quality target: a specific, measurable characteristic with limits, like P95 latency at or below 500ms at the gateway. A testable goal makes the engagement's success criteria unambiguous and the value provable. CTQs protect both sides — the seller commits to something delivery can verify, and the customer gets a clear finish line. Translating fuzzy wants into measurable targets is how the seller makes an outcome fundable.</p>",
    "copq": "<p>A Services Solutions Seller builds the business case with Cost of Poor Quality. Quantifying the rework, escalations, churned customers, and engineer-hours lost to firefighting turns a recurring problem into a dollar figure — usually far larger than the fix. Put in money, the engagement stops looking like a cost and starts looking like an obvious return, which is the argument that unlocks budget. COPQ is the seller's sharpest tool for converting a technical annoyance into a funded, executive-sponsored improvement.</p>",
    "waste": "<p>A Services Solutions Seller uses the 8 wastes to map a customer's inefficiency into a concrete, sellable improvement backlog. Walking the value stream and naming the waiting, overproduction, defects, and motion converts a vague 'we're inefficient' into prioritized opportunities with attached value. The seller can then propose the engagement that attacks the biggest waste first, with a credible lead-time payoff. The framework turns general frustration into a sequenced, fundable plan the customer can see themselves buying.</p>",
    "sipoc": "<p>A Services Solutions Seller uses a SIPOC in discovery to align stakeholders and scope the deal correctly in one page. Suppliers, Inputs, Process, Outputs, Customers laid out together exposes disputed handoffs and unmapped dependencies that would otherwise blow up mid-engagement. Agreeing the boundaries up front lets the seller scope a statement of work everyone recognizes, avoiding the scope fights that erode margin later. SIPOC gives the seller and customer a shared picture before a single line of the proposal is written.</p>",
    "value-stream": "<p>A Services Solutions Seller maps the customer's full value stream to locate where the money is really lost. When every step looks fast yet delivery takes weeks, the map shows the truth: work sits idle in queues and handoffs. That insight lets the seller propose an engagement that attacks wait time — a far bigger prize than making busy steps faster. Selling against the whole stream, not isolated steps, is how the seller frames a lead-time improvement the customer can quantify and fund.</p>",
    "pareto-chart": "<p>A Services Solutions Seller uses a Pareto chart to focus a proposal on the vital few. When a customer faces a long list of problems, the chart shows a handful of causes drive most of the pain — and the seller scopes the first engagement to exactly those. Committing to the 20% of causes behind 80% of the impact gives the customer a defensible reason to buy and a fast, visible win. Pareto turns an overwhelming wish list into a focused, high-ROI starting engagement.</p>",
    "ishikawa": "<p>A Services Solutions Seller uses an Ishikawa diagram in a workshop to demonstrate rigor and shape the right engagement. Facilitating a divergent pass across the 6 Ms surfaces candidate causes the customer never considered, positioning the seller as a partner who diagnoses before prescribing. The exercise both builds trust and reveals which root cause the engagement should target. A seller who runs a fishbone with the customer sells a solution grounded in their situation, not a generic package.</p>",
    "5-whys": "<p>A Services Solutions Seller uses 5 Whys in discovery to get past the symptom the customer thinks they need fixed. Asking why past the first plausible cause — 'we raised the memory limit' — often reaches a systemic gap the customer didn't know to ask about, which is the real, higher-value engagement. Reaching the root cause reframes the opportunity from a quick patch to a durable fix worth funding. The technique lets the seller expand a narrow ask into the improvement that actually solves the problem.</p>",
    "6-ms": "<p>A Services Solutions Seller uses the 6 Ms to run a thorough discovery that uncovers opportunities a narrow conversation would miss. Prompting across Machine, Method, Material, Measurement, People, and Environment surfaces causes — and needs — the customer hadn't articulated, sometimes revealing the real issue is measurement, not the service. The structured sweep positions the seller as rigorous and expands the pipeline of legitimate work. It turns an unstructured sales conversation into a complete map of where value can be created.</p>",
    "fmea": "<p>A Services Solutions Seller uses FMEA to sell proactive risk work before a customer's launch. Scoring failure modes by severity, occurrence, and detection surfaces a high-RPN gap — a silent backup failure, say — that becomes a compelling, evidence-based case for a hardening engagement. Selling prevention with a prioritized risk number is far stronger than selling after an incident. FMEA gives the seller a way to quantify launch risk and position the engagement that reduces it, turning caution into a fundable outcome.</p>",
    "5s": "<p>A Services Solutions Seller uses 5S to position a fast, visible early win that builds momentum for a larger program. Sorting, setting in order, shining, standardizing, and sustaining the customer's repos and environments cuts onboarding from days to hours — a tangible result the seller can point to. A quick 5S success earns the credibility and trust to sell the deeper flow and quality work. It's the low-risk land that sets up the expand.</p>",
    "standard-work": "<p>A Services Solutions Seller positions standard work as the foundation that makes every other improvement stick — and therefore the natural first engagement. Without a versioned baseline, gains evaporate when people move on, so the seller frames stabilizing and documenting the current best method as the precondition for continuous improvement. Selling the baseline first protects the value of everything sold after it. Standard work gives the seller a durable, expandable starting point instead of a one-off fix.</p>",
    "gemba": "<p>A Services Solutions Seller runs a Gemba-style discovery — observing the work where it actually happens — instead of scoping from dashboards and decks. Sitting with the customer's engineers during a real incident surfaces friction no RFP captured, revealing the higher-value engagement hiding under the stated ask. Grounding the proposal in observed reality makes it land with the people who do the work and the leaders who fund it. Real opportunities live at the Gemba, not in the summary.</p>",
    "poka-yoke": "<p>A Services Solutions Seller positions poka-yoke as an outcome customers immediately grasp: design the recurring mistake out so the error rate for that class drops to zero. Rather than selling more process or vigilance, the seller frames engineering the mistake out of the system — policy that blocks bad config, gates that can't be skipped. Mistake-proofing gives a crisp, measurable value story, and it turns reliability from a hope into a property of the platform the customer is buying.</p>",
    "andon-cord": "<p>A Services Solutions Seller uses the Andon-cord idea to sell a cultural-plus-technical engagement: give every engineer the authority to stop a bad rollout, backed by automated halts on abnormal signals. The value story is compelling — problems surface during rollout instead of in production, and quality becomes everyone's job. Positioning a blameless stop-the-line capability, not just a tool, differentiates the seller's proposal and connects a technical change to a measurable reduction in customer-facing incidents.</p>",
    "takt-time": "<p>A Services Solutions Seller uses takt time to frame a capacity-planning engagement in terms the customer's leadership trusts. Pacing work to real demand — not to how fast the team can push — calms delivery and stops overproducing unused features while starving needed ones. The seller positions predictability itself as the outcome: commitments leadership can rely on. Selling rhythm-matched-to-demand turns a vague 'we're always scrambling' complaint into a fundable improvement with a clear payoff.</p>",
    "heijunka": "<p>A Services Solutions Seller uses heijunka to sell a release-leveling engagement that attacks a customer's biggest incident driver: the end-of-quarter big-bang surge. Smoothing releases into a steady cadence removes the artificial deadlines behind most incidents, a result the seller can quantify. Positioning leveling as the fix for feast-or-famine delivery gives a clear before-and-after value story. It connects a flow change directly to fewer incidents and steadier capacity — outcomes leadership will fund.</p>",
    "one-piece-flow": "<p>A Services Solutions Seller positions one-piece flow as the modernization outcome behind trunk-based delivery: small changes shipped continuously, each easy to test, trace, and roll back. The value is concrete — mean time to detect and recover drops, and a failed deploy affects one change, not a month of bundled work. Selling small-batch flow turns a risky, high-stakes release process into a routine, low-risk habit, a transformation the customer's engineering leaders will readily invest in.</p>",
    "supermarket": "<p>A Services Solutions Seller uses the supermarket concept to sell a flow-decoupling engagement when a customer's teams swing between starved and flooded. A controlled, replenished buffer of ready work smooths handoffs without overproducing — a tangible improvement in predictability. The seller frames the outcome as steadier delivery and less firefighting at the seams between teams. It's a focused, fundable intervention with a clear operational payoff the customer can measure.</p>",
    "pull-vs-push": "<p>A Services Solutions Seller positions a shift from push to pull as an outcome leadership feels directly: work-in-progress falls, throughput rises, and people stop drowning under everything assigned at once. Letting real demand and capacity draw work in — instead of forcing it by schedule — is a change the seller can tie to measurable delivery predictability. Selling the pull system reframes 'we're overloaded' into a fundable operating-model improvement with numbers to prove it.</p>",
    "limit-wip": "<p>A Services Solutions Seller uses WIP limits to sell a counterintuitive but provable outcome: cap the work in progress and throughput rises while lead time falls. When a customer's everything is perpetually 90% done, the seller frames finishing-before-starting as the fix, backed by the flow math. It's a low-cost, high-credibility engagement that exposes the real bottleneck and delivers a fast, measurable win — an easy first step that builds appetite for deeper flow work.</p>",
    "kaizen": "<p>A Services Solutions Seller uses a Kaizen event as the perfect land: a few days, a small team, one clear target, and a shipped improvement by week's end. The fast, tangible result proves the value of continuous improvement to the customer's leadership and de-risks a larger program. Selling a time-boxed Kaizen lowers the barrier to buying and creates momentum for the expand. It turns a stubborn irritation into a demonstrable win the seller can build the next deal on.</p>",
    "kanban": "<p>A Services Solutions Seller positions a Kanban rollout as a fast way to make a customer's invisible work visible — every item, its stage, and its blockers on one board. The outcome is immediate and easy to sell: bottlenecks surface early and overload becomes impossible to ignore. It's a lightweight, low-risk starting engagement that establishes the flow visibility every later improvement depends on. Kanban gives the seller a credible, quick-win foundation for a longer improvement relationship.</p>",
    "hoshin-kanri": "<p>A Services Solutions Seller uses Hoshin Kanri to sell at the executive level, linking a customer's strategic goals to the specific initiatives, metrics, and owners that deliver them. The X-matrix reframes the conversation from tactical projects to strategy deployment — exactly where large, multi-year services investments get sponsored. Positioning improvement work as the vehicle that turns leadership's goals into execution elevates the seller from vendor to strategic partner and expands the scope of what's fundable.</p>",
    "project-charter": "<p>A Services Solutions Seller uses a project charter to lock scope, goal, and stakeholders on one page before work begins — protecting margin and the relationship. A charter stops the scope creep that erodes services profitability and gives both sides a shared definition of success to point back to. It also gives the customer's sponsor a clear, agreed basis to fund the work and judge the result. A few minutes of charter discipline up front is how the seller prevents weeks of costly drift.</p>"
  }
};
