/* iCSU Smart CI - Services Account Executive (SAE) persona examples.
   Reframes each module from the point of view of a Services Account Executive:
   the owner of the commercial account relationship who plans the portfolio of
   engagements, manages executive stakeholders, protects scope and margin, and
   drives renewals and durable account growth. Keyed by module id, per language,
   with English as the fallback. app.js merges these into the module's role-based
   examples at render time, so a module's own `saeExample` field (if ever added
   to a data file) still takes precedence. Keep each entry a single <p>
   paragraph, consistent in length and tone with the other persona fields. */
window.SAE_EXAMPLES = {
  "en": {
    "intro": "<p>A Services Account Executive reframes an account from a string of disconnected projects into a governed Continuous Improvement program. Instead of chasing the next SOW, they anchor the account plan on a repeating loop that baselines a real business metric, tests one hypothesis per cycle, and reports movement to the sponsor. Value proven every cycle makes renewals a formality and expansion a natural next step. Owning the loop, not just the deliverable, is how the SAE turns a transactional account into a durable, growing relationship.</p>",
    "belts": "<p>A Services Account Executive uses the belt ladder to structure a multi-year capability roadmap for the account. White and Yellow awareness engagements this year create the credibility and appetite for Green and Black capability work next year. Positioning belts as capability the customer's team earns on real problems — with measured results as the proof — gives the SAE a natural, outcome-anchored expansion path. It turns skilling from a one-off line item into a planned progression that grows the account over time.</p>",
    "ms-ci-cop": "<p>A Services Account Executive relies on Continuous Improvement @ Microsoft to keep delivery quality consistent across every engagement in the account. Because assessments and remediation come from peer-reviewed WAF playbooks, the SAE can promise a standard, defensible experience regardless of which team delivers. That consistency protects the relationship and the SAE's credibility with the sponsor. Patterns proven on this account also feed the community and return as reusable offers, giving the SAE more to bring back to the customer over time.</p>",
    "data-types": "<p>A Services Account Executive runs account planning on evidence, not optimism. They separate a renewal forecast (theoretical) and a usage dip (circumstantial) from measured consumption and delivery outcomes (empirical and direct), and anchor commitments to the sponsor on direct data. Presenting an account health story grounded in real numbers, not a hopeful model, protects the SAE's credibility and the renewal. Knowing which kind of data backs each claim keeps them from over-promising an account trajectory the numbers won't support.</p>",
    "convergent-divergent": "<p>A Services Account Executive resists converging an account plan on the first obvious play. In planning they stay divergent — surfacing the full set of the customer's business priorities and risks — before narrowing to the engagements the evidence justifies. Separating exploration from commitment keeps the SAE from over-scoping a portfolio the customer will resent or missing a priority that matters to the sponsor. The discipline produces an account plan shaped by the customer's real situation, which is what earns executive trust.</p>",
    "house-of-lean": "<p>A Services Account Executive uses the House of Lean to sequence a portfolio the customer can fund in stages. When earlier tools didn't stick, the SAE diagnoses the missing foundation and plans a stabilize-first engagement before flow and quality work — each phase creating the natural need for the next. The house gives the SAE a credible architecture for a land-and-expand account strategy and a way to explain to the sponsor why the sequence, not just the sum, of engagements matters.</p>",
    "dmaic": "<p>A Services Account Executive structures an engagement's commercial phases around DMAIC tollgates so the sponsor funds each stage on proven progress. Define, Measure, Analyze, Improve, Control map cleanly to fundable milestones, and the tollgates de-risk the customer's spend. This staging protects the SAE's forecast — value is demonstrated before the next phase is committed — and gives the sponsor a clear governance rhythm. DMAIC turns an open-ended 'improve reliability' mandate into a governed, milestone-based account investment.</p>",
    "pdca": "<p>A Services Account Executive frames the account's delivery as chained PDCA cycles so renewal is an easy conversation. Each change is a hypothesis, run small and checked before it scales, so the SAE can show the sponsor measured movement at every business review. Negative results become learning, not sunk cost the customer resents. Positioning the engagement as a value-proving loop means the SAE walks into the renewal with a quarter of evidence in the customer's own metrics rather than a promise.</p>",
    "a3": "<p>A Services Account Executive uses an A3 to align a fragmented stakeholder group onto one shared story before committing the account to a direction. Background, current condition, goal, root cause, countermeasures, and follow-up on one page often reveal the real problem isn't the one the sponsor first described. That clarity lets the SAE scope the right portfolio and gives the executive an at-a-glance artifact that speeds approval. The A3 is the SAE's tool for turning stakeholder noise into a fundable, agreed plan.</p>",
    "failed-hypothesis": "<p>A Services Account Executive manages the relationship when a piloted change doesn't move the metric. Rather than let a null result sour the sponsor, they position it honestly as a finding that eliminated a candidate and sharpened the next cycle — the value of a disciplined partner. Framing disconfirming evidence as progress protects trust and the renewal. An SAE who can hold an executive conversation about a well-run failed experiment is protecting the account's credibility, not defending a loss.</p>",
    "control-charts": "<p>A Services Account Executive uses the control-chart story to translate technical work into an executive outcome: fewer false alarms, faster response to real shifts, calmer teams. When an account's delivery teams over-react to noise, the SAE frames an SPC engagement around the measurable reduction in wasted effort and alert fatigue. The before-and-after gives the sponsor a clear reason the investment paid off. It converts a technical improvement into an account-health metric leadership cares about.</p>",
    "process-capability": "<p>A Services Account Executive uses Cp and Cpk to keep account commitments honest. If the sponsor wants a services outcome tied to an SLO the process can't hold, the capability numbers reveal the gap and reframe the plan toward variation reduction first. Committing the account to a defensible capability figure, not a hopeful target, protects the SAE from a broken promise and the resulting renewal risk. The number both scopes the portfolio correctly and gives the sponsor a credible basis to fund it.</p>",
    "p-value": "<p>A Services Account Executive keeps the account's value narrative credible by asking whether a reported gain is signal or noise before it goes in a business review. Claiming an engagement 'cut incidents' on a lucky week erodes sponsor trust when the metric drifts back. Grounding every reported outcome in significance, not coincidence, is what makes the SAE's account story durable — and what turns a quarterly review into evidence for renewal rather than a claim the customer quietly doubts.</p>",
    "value": "<p>A Services Account Executive plans the portfolio around the customer's Value — the outcomes their business would genuinely pay for — and steers spend away from activity that doesn't move those outcomes. Framing each engagement by the end-user value the customer feels makes the account's investment easy for the sponsor to justify internally. Value framing keeps the SAE focused on the few engagements that matter to the business, protecting both the relationship and the account's growth trajectory.</p>",
    "voc": "<p>A Services Account Executive runs Voice of the Customer at the account level rather than assuming the last conversation captured the real priorities. Structured interviews and coded feedback across the customer's stakeholders often reveal the highest-value need isn't the loudest one. Turning verbatims into ranked themes gives the SAE an evidence-based account plan and the right engagements to propose. VOC replaces guessing at the sponsor's priorities with measuring them, so the portfolio targets what the business actually values.</p>",
    "ctq": "<p>A Services Account Executive translates a sponsor's vague ambition — 'better performance,' 'more reliable' — into Critical-to-Quality targets the engagement can be measured against: specific characteristics with limits. Testable success criteria protect both sides at renewal, because value is provable rather than debatable. CTQs give the SAE unambiguous milestones to report against and the sponsor a clear finish line. Turning fuzzy executive wants into measurable targets is how the SAE makes account outcomes fundable and defensible.</p>",
    "copq": "<p>A Services Account Executive builds the account business case on Cost of Poor Quality, quantifying the rework, escalations, churn, and firefighting hours a recurring problem costs the customer each quarter. In dollars, the improvement stops looking like a cost line and becomes an obvious return — the argument that unlocks executive budget. COPQ gives the SAE the language to elevate a technical issue into a board-level investment case, turning a delivery annoyance into a funded, sponsored program.</p>",
    "waste": "<p>A Services Account Executive uses the 8 wastes to turn a customer's diffuse inefficiency into a prioritized, fundable engagement roadmap. Naming the waiting, overproduction, defects, and motion across the value stream converts 'we're inefficient' into opportunities with attached value that the SAE can sequence into the account plan. Attacking the biggest waste first delivers a fast, visible payoff that builds sponsor confidence. The framework gives the SAE a structured backlog to grow the account against.</p>",
    "sipoc": "<p>A Services Account Executive uses a SIPOC to align stakeholders and set engagement boundaries before committing the account. Suppliers, Inputs, Process, Outputs, Customers on one page exposes disputed ownership and unmapped dependencies that would otherwise surface mid-delivery as scope disputes and margin erosion. Agreeing boundaries up front lets the SAE scope work everyone recognizes and protects the relationship. SIPOC gives the account a shared picture that prevents the fights that damage trust and profitability.</p>",
    "value-stream": "<p>A Services Account Executive maps the customer's value stream to find where their business actually loses time and money. When steps look fast but delivery drags, the map reveals work idling in queues and handoffs — a far bigger prize than speeding busy steps. That insight lets the SAE plan an engagement against real wait time and report a lead-time improvement the sponsor can quantify. Selling against the whole stream elevates the account conversation from tasks to business outcomes.</p>",
    "pareto-chart": "<p>A Services Account Executive uses a Pareto chart to focus the account's first engagement on the vital few. When the customer faces a long problem list, the chart shows a handful of causes drive most of the impact, and the SAE scopes the initial work to exactly those for a fast, defensible win. Committing to the 20% behind 80% of the pain gives the sponsor a clear reason to fund and an early result that anchors the account plan's momentum.</p>",
    "ishikawa": "<p>A Services Account Executive uses an Ishikawa workshop to demonstrate rigor to the sponsor and shape the right engagement. Facilitating a divergent pass across the 6 Ms surfaces causes the customer hadn't considered, positioning the SAE and delivery team as diagnostic partners rather than order-takers. The exercise builds executive trust and reveals which root cause the account's next engagement should target — grounding the plan in the customer's situation rather than a generic template.</p>",
    "5-whys": "<p>A Services Account Executive uses 5 Whys to expand a narrow request into the engagement that actually solves the sponsor's problem. Asking why past the first plausible cause often reaches a systemic gap the customer didn't know to raise — a higher-value, more durable engagement. Reaching the root cause reframes the opportunity from a quick patch to a strategic fix worth funding. The technique helps the SAE grow the account by solving the real problem, not the symptom the customer named.</p>",
    "6-ms": "<p>A Services Account Executive uses the 6 Ms to run thorough account discovery that surfaces needs a narrow conversation would miss. Prompting across Machine, Method, Material, Measurement, People, and Environment reveals opportunities the sponsor hadn't articulated and positions the SAE as rigorous. The structured sweep expands the legitimate pipeline of work for the account. It turns an open-ended executive conversation into a complete map of where the SAE can create measurable value.</p>",
    "fmea": "<p>A Services Account Executive uses FMEA to sell proactive risk work before a customer's critical launch. A prioritized risk number — a high-RPN silent backup failure, say — gives the sponsor an evidence-based reason to fund hardening now rather than after an incident. Positioning prevention with a quantified risk case is far stronger than reacting to a failure. FMEA lets the SAE turn executive caution into a funded engagement and protect the account from the reputational damage a major incident would cause.</p>",
    "5s": "<p>A Services Account Executive uses a 5S engagement as a fast, visible early win that builds the sponsor's confidence for a larger program. Cutting onboarding from days to hours by tidying repos and environments is a tangible result the SAE can point to in the first business review. A quick 5S success earns the credibility to expand into deeper flow and quality work. It's the low-risk land that de-risks the expand and anchors the account relationship.</p>",
    "standard-work": "<p>A Services Account Executive positions standard work as the foundation that makes every later engagement's gains stick — and therefore the natural first investment. Without a versioned baseline, improvements evaporate when people move on, putting the account's value story at risk. Framing stabilization and documentation as the precondition for continuous improvement protects everything the SAE sells after it. Standard work gives the account a durable, expandable starting point rather than a fragile one-off.</p>",
    "gemba": "<p>A Services Account Executive grounds account planning in Gemba reality rather than dashboards and status decks. Having the delivery team observe the customer's work where it happens surfaces friction no report captured and reveals the higher-value engagement hiding under the stated ask. Bringing observed insight to the sponsor makes the SAE's plan land with both the people who do the work and the executives who fund it. Real account opportunities live at the Gemba, not in the summary slide.</p>",
    "poka-yoke": "<p>A Services Account Executive positions poka-yoke as an outcome the sponsor immediately values: design the recurring mistake out so its error rate drops to zero. Framing reliability as a property engineered into the platform — gates that can't be skipped, config that can't be set wrong — gives a crisp, measurable value story for the business review. Mistake-proofing converts a chronic incident source into a demonstrable improvement, strengthening the account's health narrative and the case for renewal.</p>",
    "andon-cord": "<p>A Services Account Executive uses the Andon-cord concept to frame a cultural-plus-technical engagement the sponsor can champion: authorize anyone to stop a bad rollout, backed by automated halts on abnormal signals. The outcome — problems surfacing during rollout instead of in production, quality as everyone's job — is a compelling account-health story. Positioning a blameless stop-the-line capability connects a technical change to fewer customer-facing incidents, exactly the kind of measurable result that renews accounts.</p>",
    "takt-time": "<p>A Services Account Executive uses takt time to frame predictability as the outcome the sponsor buys. Pacing delivery to real demand calms the customer's chronic scrambling and stops the overproduction that wastes their spend. The SAE positions reliable, demand-matched commitments as the value — something leadership can plan around. Selling rhythm-matched-to-demand turns a vague 'we're always behind' complaint into a fundable improvement with a payoff the sponsor can measure and defend.</p>",
    "heijunka": "<p>A Services Account Executive uses heijunka to target a customer's biggest incident driver in the account plan: the end-of-quarter big-bang release surge. Framing release leveling as the fix removes the artificial deadlines behind most incidents — a result the SAE can quantify for the sponsor. Positioning smoothing as the cure for feast-or-famine delivery gives a clear before-and-after value story and connects a flow change to steadier capacity and fewer incidents, outcomes leadership will readily fund.</p>",
    "one-piece-flow": "<p>A Services Account Executive positions one-piece flow as a modernization outcome engineering leaders will invest in: small changes shipped continuously, each easy to test, trace, and roll back. The value is concrete and reportable — faster detect-and-recover, and a failed deploy that affects one change instead of a month of bundled work. Framing small-batch flow as turning risky releases into a routine habit gives the SAE a transformation story that anchors a multi-phase account investment.</p>",
    "supermarket": "<p>A Services Account Executive uses the supermarket concept to plan a focused flow-decoupling engagement when the customer's teams swing between starved and flooded. A controlled, replenished buffer smooths the handoffs that cause firefighting at the seams — a tangible predictability gain the SAE can report. Framing steadier delivery as the outcome gives the sponsor a clear, measurable payoff. It's a targeted, fundable intervention that improves account health without a heavyweight program.</p>",
    "pull-vs-push": "<p>A Services Account Executive positions a push-to-pull shift as an operating-model improvement the sponsor feels directly: work-in-progress falls, throughput rises, and teams stop drowning. Letting real demand and capacity draw work in — rather than forcing it by schedule — is a change the SAE can tie to measurable delivery predictability. Reframing 'we're overloaded' as a fundable improvement with numbers to prove it elevates the account conversation from complaint to sponsored initiative.</p>",
    "limit-wip": "<p>A Services Account Executive uses WIP limits to deliver a fast, provable account win: cap work in progress and throughput rises while lead time falls. When the customer's work is perpetually 90% done, the SAE frames finishing-before-starting as the fix, backed by flow math the sponsor can follow. It's a low-cost, high-credibility engagement that exposes the real bottleneck and produces an early measurable result — building the sponsor's appetite for deeper flow work.</p>",
    "kaizen": "<p>A Services Account Executive uses a time-boxed Kaizen event as the ideal land in an account: a few days, a small team, a shipped result by week's end. The fast, tangible win proves continuous-improvement value to the sponsor and de-risks a larger program. A well-run Kaizen lowers the barrier to the next commitment and creates the momentum the SAE builds the account plan on — turning a stubborn irritation into a demonstrable success the sponsor can champion.</p>",
    "kanban": "<p>A Services Account Executive positions a Kanban rollout as a quick way to make the customer's invisible work visible for both teams and leadership. Bottlenecks surfacing early and overload becoming undeniable is an outcome the sponsor grasps immediately. It's a lightweight, low-risk starting engagement that establishes the flow visibility every later improvement depends on. Kanban gives the SAE a credible quick-win foundation to build a longer, growing account relationship on.</p>",
    "hoshin-kanri": "<p>A Services Account Executive uses Hoshin Kanri to operate at the executive level, linking the customer's strategic goals to the initiatives, metrics, and owners that deliver them via the X-matrix. This reframes the account from tactical projects to strategy deployment — where large, multi-year services investments are sponsored. Positioning improvement work as the vehicle that turns leadership's goals into execution elevates the SAE from vendor to strategic partner and expands what the account can fund.</p>",
    "project-charter": "<p>A Services Account Executive uses a project charter to lock scope, goal, and stakeholders on one page before delivery begins, protecting both margin and the relationship. A charter stops the scope creep that erodes services profitability and gives the sponsor a shared definition of success to fund against and judge by. It sets the SAE's engagement up for a clean value story at renewal. A few minutes of charter discipline up front prevents weeks of costly, trust-damaging drift.</p>"
  }
};
